fruits = []
a =(input("Enter fruit: "))
fruits.append(a)
a =(input("Enter fruit: "))
fruits.append(a)
a =(input("Enter fruit: "))
fruits.append(a)
a =(input("Enter fruit: "))
fruits.append(a)
a =(input("Enter fruit: "))
fruits.append(a)
a =(input("Enter fruit: "))
fruits.append(a)
print(fruits)
