marks =[]
a =int(input("Enter marks: "))
marks.append(a)
a =int(input("Enter marks: "))
marks.append(a)
a =int(input("Enter marks: "))
marks.append(a)
a =int(input("Enter marks: "))
marks.append(a)
a =int(input("Enter marks: "))
marks.append(a)
a =int(input("Enter marks: "))
marks.append(a)
marks.sort()
print(marks)
