s = set()
a = (input("Enter the number 1:"))
s.add(int(a))
a = (input("Enter the number 1:"))
s.add(int(a))
a = (input("Enter the number 1:"))
s.add(int(a))
a = (input("Enter the number 1:"))
s.add(int(a))
a = (input("Enter the number 1:"))
s.add(int(a))
a = (input("Enter the number 1:"))
s.add(int(a))
a = (input("Enter the number 1:"))
s.add(int(a))
a = (input("Enter the number 1:"))
s.add(int(a))
print(s)